import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useAsync } from "react-use";
import { PostService } from "../src/client";
import { Post } from "../src/components/Post";

const Feed: NextPage = () => {
    const posts = useAsync(PostService.getPostsPostGet)
    return (
        <div className="flex flex-col items-center">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="max-w-3xl">
                {JSON.stringify(posts)}
                {!posts.loading && posts.value?.map(post => <Post post={post} key={post.id}/>)}
            </main>

            <footer>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Feed;
